using System.Globalization;
using TaskTrackingSystem.Shared.Enums;

namespace TaskTrackingSystem.Shared.Localization;

public static class AppLocalization
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["common.workspace"] = "Workspace",
        ["common.signIn"] = "Sign In",
        ["common.signOut"] = "Sign Out",
        ["common.signOutTitle"] = "Sign Out?",
        ["common.signOutDescription"] = "Are you sure you want to sign out of Taskify?",
        ["common.cancel"] = "Cancel",
        ["common.confirm"] = "Confirm",
        ["common.confirmAction"] = "Confirm",
        ["common.areYouSure"] = "Are you sure?",
        ["common.cannotUndo"] = "This action cannot be undone.",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.ok"] = "OK",
        ["common.save"] = "Save",
        ["common.create"] = "Create",
        ["common.update"] = "Update",
        ["common.delete"] = "Delete",
        ["common.confirmSignOut"] = "Yes, Sign Out",
        ["common.listView"] = "List View",
        ["common.chartView"] = "Chart View",
        ["common.search"] = "Search",
        ["common.reset"] = "Reset",
        ["common.clear"] = "Clear",
        ["common.all"] = "All",
        ["common.loading"] = "Loading...",
        ["common.close"] = "Close",
        ["common.openNavigation"] = "Open navigation",
        ["common.closeNavigation"] = "Close navigation",
        ["common.index"] = "No.",
        ["common.exportExcel"] = "Export Excel",
        ["common.exportPdf"] = "Export PDF",
        ["common.actions"] = "Actions",
        ["common.status"] = "Status",
        ["common.priority"] = "Priority",
        ["common.assignee"] = "Assignee",
        ["common.project"] = "Project",
        ["common.task"] = "Task",
        ["common.taskProject"] = "Task / Project",
        ["common.issue"] = "Issue",
        ["common.user"] = "User",
        ["common.role"] = "Role",
        ["common.module"] = "Module",
        ["common.description"] = "Description",
        ["common.date"] = "Date",
        ["common.startDate"] = "Start Date",
        ["common.endDate"] = "End Date",
        ["common.dueDate"] = "Due Date",
        ["common.due"] = "Due",
        ["common.hours"] = "Hours",
        ["common.hoursAbbrev"] = "hrs",
        ["common.risk"] = "Risk",
        ["common.blocked"] = "Blocked",
        ["common.overdue"] = "Overdue",
        ["common.done"] = "Done",
        ["common.inProgress"] = "In Progress",
        ["common.todo"] = "To Do",
        ["common.resolved"] = "Resolved",
        ["common.clearStatus"] = "Clear",
        ["common.none"] = "None",
        ["common.unassigned"] = "Unassigned",
        ["common.noDescription"] = "No description",
        ["common.noneRecorded"] = "None recorded",
        ["common.na"] = "N/A",
        ["common.noAccessItems"] = "No access items are available for this role.",
        ["common.accessDenied"] = "Access Denied",
        ["common.error"] = "Error",
        ["common.accessDeniedDescription"] = "You do not have permission to access this page. Please contact your system administrator.",
        ["common.backToDashboard"] = "Back to Dashboard",
        ["common.noDataYet"] = "No data yet",
        ["common.createFirstEntry"] = "Create your first entry to get started.",
        ["common.loadingAuditLogs"] = "Loading audit logs...",
        ["common.loadingUsers"] = "Loading users...",
        ["common.loadingProjects"] = "Loading projects...",
        ["common.loadingTasks"] = "Loading tasks...",
        ["common.searchPlaceholder"] = "Search by name, email, username...",
        ["common.searchTasks"] = "Search Task",
        ["common.searchByUser"] = "Search by user, action, module, or details...",
        ["common.searchByTitle"] = "Search by title or project...",
        ["common.searchByTitleOrProject"] = "Search by title or project...",
        ["common.searchProjects"] = "Search projects...",
        ["common.searchTeamMembers"] = "Search team members...",
        ["common.searchProjectMembers"] = "Search project members...",
        ["common.searchIssues"] = "Search issue title, description or assignee...",
        ["common.searchByIssueAssignee"] = "Search Issues / Assignee",
        ["common.searchUsers"] = "Search Users",
        ["common.searchByName"] = "Search by name...",
        ["common.newUser"] = "New User",
        ["common.taskCode"] = "Task Code",
        ["common.selectedMember"] = "Selected member",
        ["common.loadingSpinner"] = "Loading...",
        ["common.loadingIssues"] = "Loading issues...",
        ["common.loadingTasksAndUsers"] = "Loading tasks and users...",
        ["common.loadingProjectsAndUsers"] = "Loading projects and users...",
        ["common.loadingProjectMembers"] = "Loading project members...",
        ["common.loadingMembers"] = "Loading members...",
        ["common.noResults"] = "No results found.",
        ["pagination.showing"] = "Showing",
        ["pagination.of"] = "of",
        ["pagination.results"] = "results",
        ["pagination.rowsPerPage"] = "Rows per page",
        ["pagination.firstPage"] = "First page",
        ["pagination.previousPage"] = "Previous page",
        ["pagination.nextPage"] = "Next page",
        ["pagination.lastPage"] = "Last page",
        ["common.notApplicable"] = "Not applicable",
        ["common.selectAll"] = "Select All",
        ["common.deselectAll"] = "Deselect All",
        ["common.selected"] = "selected",
        ["common.viewDetails"] = "View details",
        ["common.currentLanguage"] = "Switch language",
        ["common.languageEnglish"] = "English",
        ["common.languageBurmese"] = "Burmese",
        ["common.allTasks"] = "All tasks",
        ["common.allProjects"] = "All projects",
        ["common.allRoles"] = "All Roles",
        ["common.noProjectsFound"] = "No projects found.",
        ["common.noTasksFound"] = "No tasks found.",
        ["common.noTeamMembersFound"] = "No team members match your search criteria.",
        ["common.noMembersMatchSearch"] = "No members match the current search.",
        ["common.noTaskSelected"] = "No Task Selected",
        ["common.noProjectSelected"] = "No Project Selected",
        ["common.noProject"] = "No Project",
        ["common.currentlyAssigningTask"] = "Currently Assigning Task",
        ["common.currentlyManaging"] = "Currently Managing",
        ["common.selectProject"] = "Select Project",
        ["common.selectTask"] = "Select task...",
        ["common.issueTitle"] = "Issue Title",
        ["common.issueDescription"] = "Description",
        ["common.blockedStatus"] = "Blocked Status",
        ["common.escalationLevel"] = "Escalation Level",
        ["common.blockedBy"] = "Blocked By",
        ["common.delayReason"] = "Delay Reason",
        ["common.actualHours"] = "Actual Hours",
        ["common.estimatedHours"] = "Estimated Hours",
        ["common.assignedToMeOnly"] = "Assigned to me only",
        ["common.saveAssignment"] = "Save Assignment",
        ["common.saveAssignmentChanges"] = "Save Assignment Changes",
        ["common.saveChanges"] = "Save Changes",
        ["common.addIssue"] = "Add Issue",
        ["common.addIssueTitle"] = "Add Issue?",
        ["common.editIssue"] = "Edit Issue",
        ["common.noTaskSelectedForIssue"] = "No task selected",
        ["common.unassignedMembers"] = "Unassigned",
        ["common.removeOwnerFromTask"] = "Remove owner from this task",

        ["page.dashboard"] = "Dashboard",
        ["page.managerDashboard"] = "Manager Dashboard",
        ["page.employeeDashboard"] = "Employee Dashboard",
        ["page.projects"] = "Projects",
        ["page.projectAssignment"] = "Project Assignment",
        ["page.tasks"] = "Tasks",
        ["page.kanbanBoard"] = "Kanban Board",
        ["page.taskAssignment"] = "Task Assignment",
        ["page.taskDetails"] = "Task Details",
        ["page.issues"] = "Issues",
        ["page.addIssue"] = "Add Issue",
        ["page.taskReport"] = "Task Report",
        ["page.timeTracking"] = "Time Tracking",
        ["page.projectProgress"] = "Project Progress",
        ["page.overdueTasks"] = "Overdue Tasks",
        ["page.employeeReport"] = "Employee Report",
        ["page.rolesAccess"] = "Roles & Access",
        ["page.users"] = "Users",
        ["page.auditLogs"] = "Audit Logs",
        ["page.issueReport"] = "Issue Report",
        ["page.projectList"] = "Project List",
        ["page.taskList"] = "Task List",
        ["page.taskBacklog"] = "Task Backlog",
        ["page.roleLayouts"] = "Role Layouts",

        ["page.dashboard.desc"] = "A quick overview of work, risk, and progress.",
        ["page.managerDashboard.desc"] = "Track projects, people, and delivery health.",
        ["page.employeeDashboard.desc"] = "Focus on your tasks, due dates, and progress.",
        ["page.projects.desc"] = "Manage project plans, timelines, and assignments.",
        ["page.projectAssignment.desc"] = "Assign team members to the right projects.",
        ["page.tasks.desc"] = "Review, filter, and update work items.",
        ["page.kanbanBoard.desc"] = "Move work through status columns.",
        ["page.taskAssignment.desc"] = "Assign tasks to project members.",
        ["page.taskDetails.desc"] = "Review task progress, comments, and updates.",
        ["page.issues.desc"] = "Track blockers, notes, and daily work progress.",
        ["page.addIssue.desc"] = "Record a new issue against a task.",
        ["page.taskReport.desc"] = "Analyze task activity and export task reports.",
        ["page.timeTracking.desc"] = "Review effort by task, project, and assignee.",
        ["page.projectProgress.desc"] = "Monitor delivery health across active projects.",
        ["page.overdueTasks.desc"] = "Focus on delayed work that needs attention.",
        ["page.employeeReport.desc"] = "See how work is distributed across people.",
        ["page.rolesAccess.desc"] = "Control user roles, menus, and permissions.",
        ["page.users.desc"] = "Manage people, status, and account details.",
        ["page.auditLogs.desc"] = "Review system activity and changes.",
        ["page.issueReport.desc"] = "Track daily execution, backlog health, and issue-level effort.",
        ["page.projectList.desc"] = "Review project details and progress at a glance.",
        ["page.taskList.desc"] = "Review, filter, and update task records.",
        ["page.taskBacklog.desc"] = "See unassigned and queued work items.",
        ["page.roleLayouts.desc"] = "Review access group layouts and permissions.",

        ["dashboard.overview"] = "Overview",
        ["dashboard.welcomeBack"] = "Welcome back, {name}",
        ["dashboard.adminIntro"] = "Projects, users, and team progress at a glance.",
        ["dashboard.totalUsers"] = "Total users",
        ["dashboard.totalProjects"] = "Total projects",
        ["dashboard.activeTasks"] = "Active tasks",
        ["dashboard.completionRate"] = "Completion rate",
        ["dashboard.projectActivity"] = "Project Activity",
        ["dashboard.projectActivityDesc"] = "Active vs completed tasks per month.",
        ["dashboard.taskDistribution"] = "Task Distribution",
        ["dashboard.totalTasks"] = "{count} total tasks",
        ["dashboard.completedCount"] = "Completed: {count}",
        ["dashboard.activeCount"] = "Active: {count}",
        ["dashboard.allProjects"] = "All Projects",
        ["dashboard.projectsSnapshot"] = "A quick snapshot of the current project list.",
        ["dashboard.viewAll"] = "View all",
        ["dashboard.tasksUnit"] = "tasks",
        ["dashboard.calendar"] = "Calendar",
        ["dashboard.calendarDesc"] = "Today and upcoming project starts.",
        ["dashboard.events"] = "Events",
        ["dashboard.projectTimeline"] = "Project Timeline",
        ["dashboard.projectTimelineDesc"] = "Browse every project in a gantt view and adjust the month window below.",
        ["dashboard.from"] = "From",
        ["dashboard.to"] = "To",
        ["dashboard.noProjectsToDisplay"] = "No projects to display.",
        ["dashboard.thisMonth"] = "this month",
        ["dashboard.vsLastMonth"] = "vs last mo",
        ["dashboard.upcoming"] = "Upcoming",
        ["dashboard.active"] = "Active",
        ["dashboard.employeeTitle"] = "Employee Dashboard",
        ["dashboard.teamMember"] = "Team Member",
        ["dashboard.myWork"] = "My Work",
        ["dashboard.employeeIntro"] = "Tasks, deadlines, and your progress in one place.",
        ["dashboard.viewTasks"] = "View Tasks",
        ["dashboard.loadingDashboard"] = "Loading dashboard...",
        ["dashboard.tasksInProgressDesc"] = "Tasks currently being worked on",
        ["dashboard.noTasksInProgress"] = "No tasks in progress right now.",
        ["dashboard.todoUpcoming"] = "To Do & Upcoming",
        ["dashboard.todoUpcomingDesc"] = "Tasks waiting for action or coming up soon",
        ["dashboard.noUpcomingTasks"] = "No upcoming tasks found.",
        ["dashboard.overdueDesc"] = "Tasks past their due date",
        ["dashboard.noOverdueTasks"] = "No overdue tasks. Nice work.",
        ["dashboard.relatedTasks"] = "Related Tasks",
        ["dashboard.tasksMarkedOn"] = "Tasks marked on {date}",
        ["dashboard.noTasksForDay"] = "No tasks are scheduled for this day.",
        ["dashboard.dueSoon"] = "Due Soon",
        ["dashboard.managerTitle"] = "Manager Dashboard",
        ["dashboard.teamView"] = "Team View",
        ["dashboard.myProjects"] = "My Projects",
        ["dashboard.managerIntro"] = "Track your team, project health, and weekly task progress in one place.",
        ["dashboard.pendingTasksNotice"] = "{count} tasks are still pending.",
        ["dashboard.taskReport"] = "Task Report",
        ["dashboard.weeklyTaskProgress"] = "Weekly Task Progress",
        ["dashboard.weeklyTaskProgressDesc"] = "Completed vs pending tasks per week",
        ["dashboard.teamProgress"] = "Team Progress",
        ["dashboard.teamProgressDesc"] = "Members with active workload",
        ["dashboard.noAssignedWork"] = "No assigned work yet.",
        ["dashboard.upcomingDeadlines"] = "Upcoming Deadlines",
        ["dashboard.projectsEndingSoon"] = "Projects ending soon",
        ["dashboard.ends"] = "ends",
        ["dashboard.noUpcomingDeadlines"] = "No upcoming deadlines.",
        ["dashboard.clickViewTasks"] = "Click \"View Tasks\" to drill in",
        ["dashboard.complete"] = "Complete",
        ["dashboard.noProjectsForAccount"] = "No projects available for this account.",
        ["dashboard.activeProjects"] = "Active Projects",
        ["dashboard.totalTasksMetric"] = "Total Tasks",
        ["dashboard.teamMembers"] = "Team Members",
        ["dashboard.overdueTasks"] = "Overdue Tasks",
        ["dashboard.allActive"] = "all active",
        ["dashboard.acrossProjects"] = "across projects",
        ["dashboard.yourTeam"] = "your team",
        ["dashboard.needsAttention"] = "needs attention",
        ["dashboard.atRisk"] = "At Risk",
        ["dashboard.pending"] = "Pending",
        ["dashboard.today"] = "Today",
        ["dashboard.done"] = "Done",
        ["dashboard.daysAgo"] = "{count}d ago",
        ["dashboard.daysLeft"] = "{count}d left",
        ["dashboard.dueToday"] = "Due today",

        ["menu.DASHBOARD"] = "Dashboard",
        ["menu.DASHBOARD_ADMIN"] = "Dashboard",
        ["menu.DASHBOARD_MANAGER"] = "Dashboard",
        ["menu.DASHBOARD_EMPLOYEE"] = "Dashboard",
        ["menu.PROJECTS"] = "Projects",
        ["menu.PROJECTS_LIST"] = "Project List",
        ["menu.PROJECTS_ASSIGN"] = "Project Assign",
        ["menu.TASKS"] = "Tasks",
        ["menu.TASKS_LIST"] = "Task List",
        ["menu.TASKS_BOARD"] = "Kanban Board",
        ["menu.TASKS_ASSIGN"] = "Task Assign",
        ["menu.TASKS_BACKLOG"] = "Task Backlog",
        ["menu.ISSUES_ADD"] = "Add Issue",
        ["menu.ISSUES_LIST"] = "Issue List",
        ["menu.REPORTS"] = "Reports",
        ["menu.REPORTS_TASKS"] = "Task Report",
        ["menu.REPORTS_TIMESHEET"] = "Time Tracking",
        ["menu.REPORTS_OVERDUE"] = "Overdue Tasks",
        ["menu.REPORTS_EMPLOYEES"] = "Employee Report",
        ["menu.REPORTS_PROJECTS"] = "Project Progress",
        ["menu.REPORTS_ISSUES"] = "Issue Report",
        ["menu.AUDIT_LOGS"] = "Audit Logs",
        ["menu.USERS"] = "Users",
        ["menu.ROLES"] = "Roles",
        ["menu.DASHBOARD_WIDGETS"] = "Role Layouts",

        ["status.todo"] = "To Do",
        ["status.inprogress"] = "In Progress",
        ["status.done"] = "Done",
        ["status.overdue"] = "Overdue",
        ["status.blocked"] = "Blocked",
        ["status.clear"] = "Clear",
        ["status.resolved"] = "Resolved",
        ["status.uncompleted"] = "Uncompleted",
        ["priority.low"] = "Low",
        ["priority.medium"] = "Medium",
        ["priority.high"] = "High",
        ["status.active"] = "Active",
        ["status.inactive"] = "Inactive",
        ["role.admin"] = "Admin",
        ["role.manager"] = "Manager",
        ["role.employee"] = "Employee",
        ["field.name"] = "Name",
        ["field.title"] = "Title",
        ["field.email"] = "Email",
        ["field.phone"] = "Phone",
        ["field.created"] = "Created",
        ["field.taskCode"] = "Task Code",
        ["field.ipAddress"] = "IP Address",
        ["project.manageAll"] = "Manage all projects.",
        ["project.employeesInProject"] = "Employees in this project",
        ["project.yourAssigned"] = "Your assigned projects.",
        ["project.newProject"] = "New Project",
        ["project.editProject"] = "Edit Project",
        ["project.createProject"] = "Create Project",
        ["project.noProjectsYet"] = "No projects yet",
        ["project.createFirstProject"] = "Create your first project to get started.",
        ["project.noAssignedProjects"] = "You have not been assigned to any projects.",
        ["project.projectName"] = "Project name",
        ["project.projectDescriptionOptional"] = "Project description (optional)",
        ["project.updateTitle"] = "Update Project?",
        ["project.updateConfirm"] = "Are you sure you want to update this project?",
        ["project.createTitle"] = "Create Project?",
        ["project.createConfirm"] = "Are you sure you want to create this project?",
        ["project.deleteTitle"] = "Delete Project?",
        ["project.deleteConfirm"] = "Are you sure you want to delete this project? This action cannot be undone.",
        ["project.created"] = "Project created successfully!",
        ["project.updated"] = "Project updated successfully!",
        ["project.deleted"] = "Project deleted successfully!",
        ["project.failedDelete"] = "Failed to delete project.",
        ["task.manageAll"] = "View and manage all tasks across projects.",
        ["task.filterByProject"] = "Filter by Project",
        ["task.yourAssigned"] = "Your assigned tasks.",
        ["task.newTask"] = "New Task",
        ["task.editTask"] = "Edit Task",
        ["task.createTask"] = "Create Task",
        ["task.noTasksYet"] = "No tasks yet",
        ["task.createFirstTask"] = "Create your first task to get started.",
        ["task.taskTitle"] = "Task title",
        ["task.taskDescription"] = "Task description",
        ["task.selectProject"] = "Select project...",
        ["task.loadingBoard"] = "Loading board...",
        ["task.dragHint"] = "Drag tasks between columns to update their status.",
        ["task.viewingArchived"] = "Viewing archived tasks.",
        ["task.backToBoard"] = "Back to Board",
        ["task.archivedTasks"] = "Archived Tasks",
        ["task.archived"] = "Archived",
        ["task.dropTasksHere"] = "Drop tasks here",
        ["task.noTasks"] = "No tasks",
        ["task.of"] = "of",
        ["task.due"] = "Due",
        ["task.previousPage"] = "Previous page",
        ["task.nextPage"] = "Next page",
        ["task.createTitle"] = "Create Task?",
        ["task.createConfirm"] = "Are you sure you want to create this task?",
        ["task.updateTitle"] = "Update Task?",
        ["task.updateConfirm"] = "Are you sure you want to update this task?",
        ["task.deleteTitle"] = "Delete Task?",
        ["task.deleteConfirm"] = "Are you sure you want to delete this task? This action cannot be undone.",
        ["task.archiveDoneTitle"] = "Archive Done Tasks?",
        ["task.archiveDoneInProject"] = "Archive {count} Done task(s) in this project? Archived tasks will be hidden from active views.",
        ["task.archiveDoneAll"] = "Archive {count} Done task(s) across all visible projects? Archived tasks will be hidden from active views.",
        ["task.noDoneToArchive"] = "No Done tasks to archive.",
        ["task.created"] = "Task created successfully!",
        ["task.updated"] = "Task updated successfully!",
        ["task.deleted"] = "Task deleted successfully!",
        ["task.failedCreate"] = "Failed to create task.",
        ["task.failedDelete"] = "Failed to delete task.",
        ["task.failedMove"] = "Failed to move task. Please try again.",
        ["task.failedArchiveDone"] = "Failed to archive Done tasks.",
        ["task.archivedOneDone"] = "Archived 1 Done task.",
        ["task.archivedManyDone"] = "Archived {count} Done tasks.",
        ["task.archive"] = "Archive",
        ["role.rolesAccess"] = "Roles & Access",
        ["role.rolesAccessDesc"] = "Manage roles, assign access and permissions, and control visibility.",
        ["role.newRole"] = "New Role",
        ["role.editRole"] = "Edit Role",
        ["role.createNewRole"] = "Create New Role",
        ["role.roleName"] = "Role Name",
        ["role.searchByName"] = "Search roles by name...",
        ["role.loadingRoles"] = "Loading roles...",
        ["role.noRolesYet"] = "No roles yet",
        ["role.createFirstRole"] = "Create your first role to get started.",
        ["role.manageAccess"] = "Manage Access",
        ["role.access"] = "Access",
        ["role.assignAccess"] = "Assign Access",
        ["role.accessHint"] = "Pages control where the role can go. Actions control what it can do.",
        ["role.createHint"] = "Choose what this role can see and do on the right. It will be saved with the role.",
        ["role.descriptionPlaceholder"] = "What can this role do?",
        ["role.examplePlaceholder"] = "e.g. Manager, Viewer",
        ["role.updateTitle"] = "Update Role?",
        ["role.updateConfirm"] = "Are you sure you want to update this role?",
        ["role.createTitle"] = "Create Role?",
        ["role.createConfirm"] = "Are you sure you want to create this role?",
        ["role.deleteTitle"] = "Delete Role?",
        ["role.deleteConfirm"] = "Are you sure you want to delete this role? This action cannot be undone.",
        ["role.cannotDeleteTitle"] = "Cannot Delete Role",
        ["role.cannotDeleteUsers"] = "You can't delete this role because there are {count} users in this role.",
        ["role.created"] = "Role created successfully!",
        ["role.updated"] = "Role updated successfully!",
        ["role.deleted"] = "Role deleted successfully!",
        ["role.failedDelete"] = "Failed to delete role.",
        ["role.saveAccess"] = "Save Access",
        ["role.accessConfigured"] = "Configure access and permissions",
        ["role.permissionsHint"] = "Menus open pages. Permissions unlock actions.",
        ["role.changeApplyAfterSave"] = "Changes apply immediately after saving.",
        ["role.noAccessItemsFound"] = "No access items found in database.",
        ["role.noPagesMatchSearch"] = "No pages or permissions match your search.",
        ["role.pagePermissionHint"] = "Page access lets the role open this section. Permissions let it use the buttons and actions inside.",
        ["role.nothingInsidePage"] = "Nothing else is available inside this page.",
        ["role.crudPermissions"] = "CRUD permissions for this page",
        ["role.willBeSaved"] = "will be saved",
        ["role.selectedItems"] = "{count} selected item(s)",
        ["role.accessSaved"] = "Access saved successfully.",
        ["role.failedLoadAccess"] = "Failed to load access items. Please try again.",
        ["role.failedSaveAccess"] = "Failed to save access.",
        ["common.unknown"] = "Unknown",
        ["common.saving"] = "Saving...",
        ["common.creating"] = "Creating...",
        ["common.searchRoles"] = "Search Roles",
        ["common.searchTasksByTitle"] = "Search tasks by title...",
        ["common.allStatuses"] = "All Statuses",
        ["common.allPriorities"] = "All Priorities",
        ["common.budgetedHours"] = "Budgeted Hours",
        ["common.budgetedHoursOptional"] = "Budgeted hours (optional)",

        ["action.search"] = "Search",
        ["action.reset"] = "Reset",
        ["action.exportExcel"] = "Export Excel",
        ["action.exportPdf"] = "Export PDF",
        ["action.edit"] = "Edit",
        ["action.delete"] = "Delete",
        ["action.add"] = "Add",
        ["action.create"] = "Create",
        ["action.update"] = "Update",
        ["action.save"] = "Save",
        ["action.assign"] = "Assign",
        ["action.viewTasks"] = "View Tasks",
        ["action.archiveDone"] = "Archive Done",
        ["action.clear"] = "Clear",

        ["result.loading"] = "Loading...",
        ["result.saved"] = "Saved successfully.",
        ["result.created"] = "Created successfully.",
        ["result.updated"] = "Updated successfully.",
        ["result.deleted"] = "Deleted successfully.",

        ["report.periodFilter"] = "Period",
        ["report.daily"] = "Daily (Today)",
        ["report.monthly"] = "Monthly (This Month)",
        ["report.yearly"] = "Yearly (This Year)",
        ["report.customRange"] = "Custom Range",
        ["report.selectedProject"] = "Selected project",
        ["report.openIssues"] = "Open issues",
        ["report.lastActivity"] = "Last activity",
        ["report.noTasksFound"] = "No Tasks Found",
        ["report.noTasksFoundDesc"] = "There are no tasks matching your filters. Try adjusting your search query or filters.",
        ["report.noIssuesFound"] = "No issues found",
        ["report.noIssuesFoundDesc"] = "No issues matched the current report filters.",
        ["report.healthCritical"] = "Critical",
        ["report.healthAtRisk"] = "At Risk",
        ["report.healthGood"] = "Healthy",
        ["report.delay"] = "Delay",
        ["report.blockedBy"] = "Blocked by",
        ["report.noEffortEntries"] = "No effort entries",
        ["report.noEffortEntriesDesc"] = "No timesheet effort entries matched your filters.",
        ["report.totalEstimatedEffort"] = "Total Estimated Effort",
        ["report.variance"] = "Variance",
        ["report.utilization"] = "Utilization",
        ["report.timesheetEntries"] = "timesheet issue entry(s)",
        ["report.delayType"] = "Delay Type",
        ["report.days"] = "days",
        ["report.dueIn"] = "Due in",
        ["report.noReasonRecorded"] = "No reason recorded",
        ["report.noOverdueTasksDesc"] = "Great! No tasks are overdue or at risk based on the current filters.",
        ["report.aheadOfSchedule"] = "Ahead of Schedule",
        ["report.blockedOverdue"] = "Blocked / Overdue",
        ["report.noProjectData"] = "No project data found matching criteria.",
        ["report.employee"] = "Employee",
        ["report.assignedIssues"] = "Assigned Issues",
        ["report.openOverdue"] = "Open / Overdue",
        ["report.workload"] = "Workload",
        ["report.trend"] = "Trend",
        ["report.workloadHigh"] = "High",
        ["report.workloadLight"] = "Light",
        ["report.workloadBalanced"] = "Balanced",
        ["report.trendImproving"] = "Improving",
        ["report.trendDeclining"] = "Declining",
        ["report.trendStable"] = "Stable",
        ["report.noEmployeeData"] = "No employee data found matching criteria.",
        ["report.estimatedVsActual"] = "Estimated vs actual effort",
        ["report.utilizationGauge"] = "Utilization gauge",
        ["report.estimateAccuracy"] = "Estimate accuracy",
        ["report.effortByProject"] = "Effort by project",
        ["report.effortLeaderboard"] = "Effort leaderboard",
        ["report.workloadHeatmap"] = "Workload heatmap",
        ["report.capacitySupportList"] = "Capacity support list",
        ["report.completedVsOpenIssues"] = "Completed vs open issues",
        ["report.overdueSupport"] = "Overdue support",
        ["report.completionPattern"] = "Completion pattern",
        ["report.projectHealthMatrix"] = "Project health matrix",
        ["report.completionVsRisk"] = "Completion vs risk",
        ["report.timelineSummary"] = "Timeline summary",
        ["report.openOverdueBlockingIssues"] = "Open, overdue, and blocking issues by project",
        ["report.topAtRiskProjects"] = "Top at-risk projects",
        ["report.keyInsights"] = "Key Insights",

        ["validation.startDateRequired"] = "Start date is required.",
        ["validation.dueDateRequired"] = "Due date is required.",
        ["validation.dueDateBeforeStart"] = "Due date cannot be earlier than start date.",
        ["validation.projectNameRequired"] = "Project name is required.",
        ["validation.endDateBeforeStart"] = "End date cannot be before start date.",
        ["validation.taskTitleRequired"] = "Task title is required.",
        ["validation.selectProjectRequired"] = "Please select a project.",
        ["validation.selectTaskRequired"] = "Please select a task.",
        ["validation.issueTitleRequired"] = "Issue title is required.",
        ["validation.roleNameRequired"] = "Role name is required.",
        ["validation.passwordMinLength"] = "Password must be at least 6 characters.",
        ["validation.usernameMinLength"] = "Username must be at least 3 characters long.",
        ["validation.usernameNoSpaces"] = "Username cannot contain spaces.",
        ["validation.usernameInvalidCharacters"] = "Username cannot contain spaces, and can only contain letters, numbers, underscores (_), and periods (.)",
        ["validation.passwordMinLengthRule"] = "Password must be at least 8 characters long.",
        ["validation.passwordComplexityRule"] = "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character."
    };

    private static readonly IReadOnlyDictionary<string, string> Burmese = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["common.workspace"] = "အလုပ်ခွင်",
        ["common.signIn"] = "အကောင့်ဝင်ရန်",
        ["common.signOut"] = "အကောင့်ထွက်ရန်",
        ["common.signOutTitle"] = "အကောင့်ထွက်မလား?",
        ["common.signOutDescription"] = "Taskify မှ အကောင့်ထွက်ရန် သေချာပါသလား?",
        ["common.cancel"] = "မလုပ်တော့ပါ",
        ["common.confirm"] = "အတည်ပြုမည်",
        ["common.confirmAction"] = "အတည်ပြုမည်",
        ["common.areYouSure"] = "သင် သေချာပါသလား?",
        ["common.cannotUndo"] = "ဤလုပ်ဆောင်ချက်ကို ပြန်ပြင်မရပါ။",
        ["common.yes"] = "ဟုတ်ကဲ့",
        ["common.no"] = "မဟုတ်ပါ",
        ["common.ok"] = "အိုကေ",
        ["common.save"] = "သိမ်းမည်",
        ["common.create"] = "ဖန်တီးမည်",
        ["common.update"] = "အပ်ဒိတ်လုပ်မည်",
        ["common.delete"] = "ဖျက်မည်",
        ["common.confirmSignOut"] = "ဟုတ်ကဲ့၊ အကောင့်ထွက်မည်",
        ["common.listView"] = "စာရင်းမြင်ကွင်း",
        ["common.chartView"] = "ဇယားမြင်ကွင်း",
        ["common.search"] = "ရှာမည်",
        ["common.reset"] = "ပြန်လည်သတ်မှတ်မည်",
        ["common.clear"] = "ရှင်းမည်",
        ["common.all"] = "အားလုံး",
        ["common.loading"] = "ဖွင့်နေသည်...",
        ["common.close"] = "ပိတ်မည်",
        ["common.openNavigation"] = "မီနူးဖွင့်ရန်",
        ["common.closeNavigation"] = "မီနူးပိတ်ရန်",
        ["common.index"] = "နံပါတ်",
        ["common.exportExcel"] = "Excel ထုတ်မည်",
        ["common.exportPdf"] = "PDF ထုတ်မည်",
        ["common.actions"] = "လုပ်ဆောင်ချက်များ",
        ["common.status"] = "အခြေအနေ",
        ["common.priority"] = "ဦးစားပေး",
        ["common.assignee"] = "တာဝန်ယူသူ",
        ["common.project"] = "စီမံကိန်း",
        ["common.task"] = "လုပ်ငန်း",
        ["common.taskProject"] = "လုပ်ငန်း / စီမံကိန်း",
        ["common.issue"] = "ပြဿနာ",
        ["common.user"] = "အသုံးပြုသူ",
        ["common.role"] = "အခန်းကဏ္ဍ",
        ["common.module"] = "မော်ဂျူး",
        ["common.description"] = "ဖော်ပြချက်",
        ["common.date"] = "ရက်စွဲ",
        ["common.startDate"] = "စတင်ရက်",
        ["common.endDate"] = "ပြီးဆုံးရက်",
        ["common.dueDate"] = "ပြီးဆုံးရန်ရက်",
        ["common.due"] = "ပြီးဆုံးရက်",
        ["common.hours"] = "နာရီ",
        ["common.hoursAbbrev"] = "နာရီ",
        ["common.risk"] = "အန္တရာယ်",
        ["common.blocked"] = "ပိတ်ဆို့ထားသည်",
        ["common.overdue"] = "နောက်ကျနေသည်",
        ["common.done"] = "ပြီးဆုံး",
        ["common.inProgress"] = "ဆောင်ရွက်နေသည်",
        ["common.todo"] = "လုပ်ရန်",
        ["common.resolved"] = "ဖြေရှင်းပြီး",
        ["common.clearStatus"] = "ရှင်းလင်း",
        ["common.none"] = "မရှိ",
        ["common.unassigned"] = "မချမှတ်ရသေး",
        ["common.noDescription"] = "ဖော်ပြချက်မရှိ",
        ["common.noneRecorded"] = "မှတ်တမ်းမရှိ",
        ["common.na"] = "မသက်ဆိုင်ပါ",
        ["common.noAccessItems"] = "ဤအခန်းကဏ္ဍအတွက် ဝင်ရောက်ခွင့်မရှိသေးပါ။",
        ["common.accessDenied"] = "ဝင်ရောက်ခွင့် မရှိပါ",
        ["common.error"] = "အမှား",
        ["common.accessDeniedDescription"] = "ဤစာမျက်နှာသို့ ဝင်ရောက်ရန် သင်၌ ခွင့်ပြုချက်မရှိပါ။ စနစ်စီမံသူကို ဆက်သွယ်ပါ။",
        ["common.backToDashboard"] = "ဒက်ရှ်ဘုတ်သို့ ပြန်သွားမည်",
        ["common.noDataYet"] = "အချက်အလက် မရှိသေးပါ",
        ["common.createFirstEntry"] = "စတင်ရန် ပထမဆုံး အချက်အလက်ကို ဖန်တီးပါ။",
        ["common.loadingAuditLogs"] = "မှတ်တမ်းများ ဖွင့်နေသည်...",
        ["common.loadingUsers"] = "အသုံးပြုသူများ ဖွင့်နေသည်...",
        ["common.loadingProjects"] = "စီမံကိန်းများ ဖွင့်နေသည်...",
        ["common.loadingTasks"] = "လုပ်ငန်းများ ဖွင့်နေသည်...",
        ["common.searchPlaceholder"] = "အမည်၊ အီးမေးလ်၊ အသုံးပြုသူအမည်ဖြင့် ရှာပါ...",
        ["common.searchTasks"] = "အလုပ်ရှာရန်",
        ["common.searchByTitleOrProject"] = "ခေါင်းစဉ် သို့မဟုတ် စီမံကိန်းဖြင့် ရှာပါ...",
        ["common.searchByUser"] = "အသုံးပြုသူ၊ လုပ်ဆောင်ချက်၊ မော်ဂျူး သို့မဟုတ် အသေးစိတ်ဖြင့် ရှာပါ...",
        ["common.searchByTitle"] = "ခေါင်းစဉ် သို့မဟုတ် စီမံကိန်းအမည်ဖြင့် ရှာပါ...",
        ["common.searchProjects"] = "စီမံကိန်းများ ရှာပါ...",
        ["common.searchTeamMembers"] = "အဖွဲ့ဝင်များ ရှာပါ...",
        ["common.searchProjectMembers"] = "စီမံကိန်းအဖွဲ့ဝင်များ ရှာပါ...",
        ["common.searchIssues"] = "ပြဿနာ ခေါင်းစဉ်၊ ဖော်ပြချက် သို့မဟုတ် တာဝန်ယူသူဖြင့် ရှာပါ...",
        ["common.searchByIssueAssignee"] = "ပြဿနာ / တာဝန်ယူသူ ရှာရန်",
        ["common.searchUsers"] = "အသုံးပြုသူများ ရှာရန်",
        ["common.searchByName"] = "အမည်ဖြင့် ရှာပါ...",
        ["common.newUser"] = "အသုံးပြုသူအသစ်",
        ["common.taskCode"] = "လုပ်ငန်းကုဒ်",
        ["common.selectedMember"] = "ရွေးထားသော အဖွဲ့ဝင်",
        ["common.loadingSpinner"] = "ဖွင့်နေသည်...",
        ["common.loadingIssues"] = "ပြဿနာများ ဖွင့်နေသည်...",
        ["common.loadingTasksAndUsers"] = "လုပ်ငန်းများနှင့် အသုံးပြုသူများ ဖွင့်နေသည်...",
        ["common.loadingProjectsAndUsers"] = "စီမံကိန်းများနှင့် အသုံးပြုသူများ ဖွင့်နေသည်...",
        ["common.loadingProjectMembers"] = "စီမံကိန်းအဖွဲ့ဝင်များ ဖွင့်နေသည်...",
        ["common.loadingMembers"] = "အဖွဲ့ဝင်များ ဖွင့်နေသည်...",
        ["common.noResults"] = "ရလဒ်မတွေ့ပါ။",
        ["pagination.showing"] = "ပြသနေသည်",
        ["pagination.of"] = "စုစုပေါင်း",
        ["pagination.results"] = "ရလဒ်",
        ["pagination.rowsPerPage"] = "တစ်မျက်နှာအရေအတွက်",
        ["pagination.firstPage"] = "ပထမစာမျက်နှာ",
        ["pagination.previousPage"] = "ရှေ့စာမျက်နှာ",
        ["pagination.nextPage"] = "နောက်စာမျက်နှာ",
        ["pagination.lastPage"] = "နောက်ဆုံးစာမျက်နှာ",
        ["common.notApplicable"] = "မသက်ဆိုင်ပါ",
        ["common.selectAll"] = "အားလုံးရွေးမည်",
        ["common.deselectAll"] = "အားလုံးဖြုတ်မည်",
        ["common.selected"] = "ရွေးထားသည်",
        ["common.viewDetails"] = "အသေးစိတ်ကြည့်မည်",
        ["common.currentLanguage"] = "ဘာသာစကားပြောင်းရန်",
        ["common.languageEnglish"] = "အင်္ဂလိပ်",
        ["common.languageBurmese"] = "မြန်မာ",
        ["common.allTasks"] = "အလုပ်အားလုံး",
        ["common.allProjects"] = "စီမံကိန်းအားလုံး",
        ["common.allRoles"] = "အခန်းကဏ္ဍအားလုံး",
        ["common.noProjectsFound"] = "စီမံကိန်းမတွေ့ပါ။",
        ["common.noTasksFound"] = "လုပ်ငန်းမတွေ့ပါ။",
        ["common.noTeamMembersFound"] = "သင်ရှာဖွေသည့် အဖွဲ့ဝင် မရှိပါ။",
        ["common.noMembersMatchSearch"] = "လက်ရှိရှာဖွေမှုနှင့် ကိုက်ညီသည့် အဖွဲ့ဝင် မရှိပါ။",
        ["common.noTaskSelected"] = "လုပ်ငန်း မရွေးထားပါ",
        ["common.noProjectSelected"] = "စီမံကိန်း မရွေးထားပါ",
        ["common.noProject"] = "စီမံကိန်း မရှိပါ",
        ["common.currentlyAssigningTask"] = "လက်ရှိ ချထားနေသော လုပ်ငန်း",
        ["common.currentlyManaging"] = "လက်ရှိ စီမံနေသည်",
        ["common.selectProject"] = "စီမံကိန်း ရွေးရန်",
        ["common.selectTask"] = "လုပ်ငန်း ရွေးရန်...",
        ["common.issueTitle"] = "ပြဿနာ ခေါင်းစဉ်",
        ["common.issueDescription"] = "ဖော်ပြချက်",
        ["common.blockedStatus"] = "ပိတ်ဆို့မှု အခြေအနေ",
        ["common.escalationLevel"] = "အဆင့်တိုးမှု အဆင့်",
        ["common.blockedBy"] = "ပိတ်ဆို့နေသူ",
        ["common.delayReason"] = "နှောင့်နှေးရသည့် အကြောင်းရင်း",
        ["common.actualHours"] = "တကယ့် နာရီ",
        ["common.estimatedHours"] = "ခန့်မှန်း နာရီ",
        ["common.assignedToMeOnly"] = "ကျွန်ုပ်ထံပဲ ချထားထားသည်",
        ["common.saveAssignment"] = "တာဝန်ချမှု သိမ်းမည်",
        ["common.saveAssignmentChanges"] = "တာဝန်ချမှု ပြောင်းလဲချက်များ သိမ်းမည်",
        ["common.saveChanges"] = "ပြောင်းလဲချက်များ သိမ်းမည်",
        ["common.addIssue"] = "ပြဿနာ ထည့်မည်",
        ["common.addIssueTitle"] = "ပြဿနာ ထည့်မည်လား?",
        ["common.editIssue"] = "ပြဿနာ ပြင်မည်",
        ["common.removeOwnerFromTask"] = "ဤလုပ်ငန်းမှ ပိုင်ရှင်ကို ဖယ်ရှားမည်",

        ["page.dashboard"] = "ဒက်ရှ်ဘုတ်",
        ["page.managerDashboard"] = "မန်နေဂျာ ဒက်ရှ်ဘုတ်",
        ["page.employeeDashboard"] = "ဝန်ထမ်း ဒက်ရှ်ဘုတ်",
        ["page.projects"] = "စီမံကိန်းများ",
        ["page.projectAssignment"] = "စီမံကိန်း ခွဲဝေခြင်း",
        ["page.tasks"] = "လုပ်ငန်းများ",
        ["page.kanbanBoard"] = "ကန်ဘန်းဘုတ်",
        ["page.taskAssignment"] = "လုပ်ငန်း ခွဲဝေခြင်း",
        ["page.taskDetails"] = "လုပ်ငန်း အသေးစိတ်",
        ["page.issues"] = "ပြဿနာများ",
        ["page.addIssue"] = "ပြဿနာ ထည့်ရန်",
        ["page.taskReport"] = "လုပ်ငန်း အစီရင်ခံစာ",
        ["page.timeTracking"] = "အချိန်မှတ်တမ်း",
        ["page.projectProgress"] = "စီမံကိန်း တိုးတက်မှု",
        ["page.overdueTasks"] = "နောက်ကျ လုပ်ငန်းများ",
        ["page.employeeReport"] = "ဝန်ထမ်း အစီရင်ခံစာ",
        ["page.rolesAccess"] = "အခန်းကဏ္ဍနှင့် ဝင်ခွင့်",
        ["page.users"] = "အသုံးပြုသူများ",
        ["page.auditLogs"] = "စနစ်မှတ်တမ်းများ",
        ["page.issueReport"] = "ပြဿနာ အစီရင်ခံစာ",
        ["page.projectList"] = "စီမံကိန်းစာရင်း",
        ["page.taskList"] = "လုပ်ငန်းစာရင်း",
        ["page.taskBacklog"] = "လုပ်ငန်း နောက်ခံစာရင်း",
        ["page.roleLayouts"] = "အခန်းကဏ္ဍ အပြင်အဆင်များ",

        ["page.dashboard.desc"] = "အလုပ်များ၊ အန္တရာယ်များနှင့် တိုးတက်မှုများကို တစ်ချက်ကြည့်နိုင်သည်။",
        ["page.managerDashboard.desc"] = "စီမံကိန်းများ၊ လူအင်အားနှင့် ပေးပို့မှုအခြေအနေကို စောင့်ကြည့်ပါ။",
        ["page.employeeDashboard.desc"] = "သင့်လုပ်ငန်းများ၊ သတ်မှတ်ရက်နှင့် တိုးတက်မှုများကို အာရုံစိုက်ပါ။",
        ["page.projects.desc"] = "စီမံကိန်းအစီအစဉ်၊ အချိန်ဇယားနှင့် ခွဲဝေမှုများကို စီမံပါ။",
        ["page.projectAssignment.desc"] = "အဖွဲ့ဝင်များကို သင့်တော်သော စီမံကိန်းများသို့ ခွဲဝေပါ။",
        ["page.tasks.desc"] = "လုပ်ငန်းများကို ကြည့်ရှု၊ စစ်ထုတ်၊ အပ်ဒိတ်လုပ်ပါ။",
        ["page.kanbanBoard.desc"] = "အလုပ်များကို အခြေအနေကော်လံများအတိုင်း ရွှေ့ပါ။",
        ["page.taskAssignment.desc"] = "လုပ်ငန်းများကို စီမံကိန်းအဖွဲ့ဝင်များသို့ ခွဲဝေပါ။",
        ["page.taskDetails.desc"] = "လုပ်ငန်းတိုးတက်မှု၊ မှတ်ချက်များနှင့် အပ်ဒိတ်များကို ကြည့်ရှုပါ။",
        ["page.issues.desc"] = "ပိတ်ဆို့မှုများ၊ မှတ်စုများနှင့် နေ့စဉ် အလုပ်တိုးတက်မှုကို ခြေရာခံပါ။",
        ["page.addIssue.desc"] = "လုပ်ငန်းတစ်ခုအတွက် ပြဿနာအသစ်ကို မှတ်တမ်းတင်ပါ။",
        ["page.taskReport.desc"] = "လုပ်ငန်းလှုပ်ရှားမှုကို ခွဲခြမ်းပြီး အစီရင်ခံစာများ ထုတ်ပါ။",
        ["page.timeTracking.desc"] = "လုပ်ငန်း၊ စီမံကိန်းနှင့် တာဝန်ယူသူအလိုက် အားထုတ်မှုကို ကြည့်ရှုပါ။",
        ["page.projectProgress.desc"] = "လက်ရှိ စီမံကိန်းများ၏ ပေးပို့မှုအခြေအနေကို စောင့်ကြည့်ပါ။",
        ["page.overdueTasks.desc"] = "အရေးပေါ် အာရုံစိုက်ရန် လိုသည့် နောက်ကျလုပ်ငန်းများကို ကြည့်ပါ။",
        ["page.employeeReport.desc"] = "အလုပ်တာဝန်များ လူတစ်ဦးချင်းစီအလိုက် မည်သို့ ဖြန့်ဝေထားသည်ကို ကြည့်ပါ။",
        ["page.rolesAccess.desc"] = "အသုံးပြုသူအခန်းကဏ္ဍ၊ မီနူးများနှင့် ခွင့်ပြုချက်များကို ထိန်းချုပ်ပါ။",
        ["page.users.desc"] = "လူများ၊ အခြေအနေများနှင့် အကောင့်အသေးစိတ်များကို စီမံပါ။",
        ["page.auditLogs.desc"] = "စနစ်လှုပ်ရှားမှုများနှင့် ပြောင်းလဲမှုများကို ပြန်လည်ကြည့်ရှုပါ။",
        ["page.issueReport.desc"] = "နေ့စဉ် ဆောင်ရွက်မှု၊ နောက်ကျမှုနှင့် ပြဿနာအလိုက် အားထုတ်မှုကို ခြေရာခံပါ။",
        ["page.projectList.desc"] = "စီမံကိန်းအသေးစိတ်နှင့် တိုးတက်မှုကို တစ်ချက်ကြည့်ပါ။",
        ["page.taskList.desc"] = "လုပ်ငန်းမှတ်တမ်းများကို ကြည့်ရှု၊ စစ်ထုတ်၊ အပ်ဒိတ်လုပ်ပါ။",
        ["page.taskBacklog.desc"] = "မခွဲဝေသေးသော နှင့် စောင့်ဆိုင်းနေသော အလုပ်များကို ကြည့်ပါ။",
        ["page.roleLayouts.desc"] = "ဝင်ခွင့်အုပ်စု ပုံစံများနှင့် ခွင့်ပြုချက်များကို ကြည့်ပါ။",

        ["dashboard.overview"] = "အနှစ်ချုပ်",
        ["dashboard.welcomeBack"] = "ပြန်လည်ကြိုဆိုပါတယ်၊ {name}",
        ["dashboard.adminIntro"] = "စီမံကိန်းများ၊ အသုံးပြုသူများနှင့် အဖွဲ့တိုးတက်မှုကို တစ်ချက်ကြည့်နိုင်သည်။",
        ["dashboard.totalUsers"] = "အသုံးပြုသူ စုစုပေါင်း",
        ["dashboard.totalProjects"] = "စီမံကိန်း စုစုပေါင်း",
        ["dashboard.activeTasks"] = "လက်ရှိအလုပ်များ",
        ["dashboard.completionRate"] = "ပြီးစီးမှုနှုန်း",
        ["dashboard.projectActivity"] = "စီမံကိန်း လှုပ်ရှားမှု",
        ["dashboard.projectActivityDesc"] = "လအလိုက် လက်ရှိနှင့် ပြီးစီးသောအလုပ်များ။",
        ["dashboard.taskDistribution"] = "အလုပ်များ ခွဲဝေမှု",
        ["dashboard.totalTasks"] = "အလုပ် စုစုပေါင်း {count} ခု",
        ["dashboard.completedCount"] = "ပြီးစီးပြီး: {count}",
        ["dashboard.activeCount"] = "လက်ရှိ: {count}",
        ["dashboard.allProjects"] = "စီမံကိန်းအားလုံး",
        ["dashboard.projectsSnapshot"] = "လက်ရှိစီမံကိန်းစာရင်းကို အမြန်ကြည့်ရန်။",
        ["dashboard.viewAll"] = "အားလုံးကြည့်ရန်",
        ["dashboard.tasksUnit"] = "အလုပ်",
        ["dashboard.calendar"] = "ပြက္ခဒိန်",
        ["dashboard.calendarDesc"] = "ယနေ့နှင့် မကြာမီစမည့် စီမံကိန်းများ။",
        ["dashboard.events"] = "ဖြစ်ရပ်များ",
        ["dashboard.projectTimeline"] = "စီမံကိန်း အချိန်ဇယား",
        ["dashboard.projectTimelineDesc"] = "စီမံကိန်းအားလုံးကို Gantt ပုံစံဖြင့် ကြည့်ပြီး အောက်တွင် လအပိုင်းအခြားကို ပြင်ဆင်ပါ။",
        ["dashboard.from"] = "မှ",
        ["dashboard.to"] = "အထိ",
        ["dashboard.noProjectsToDisplay"] = "ပြသရန် စီမံကိန်း မရှိပါ။",
        ["dashboard.thisMonth"] = "ယခုလ",
        ["dashboard.vsLastMonth"] = "ပြီးခဲ့သည့်လနှင့် နှိုင်းယှဉ်",
        ["dashboard.upcoming"] = "မကြာမီစမည်",
        ["dashboard.active"] = "လက်ရှိ",
        ["dashboard.employeeTitle"] = "ဝန်ထမ်း ဒက်ရှ်ဘုတ်",
        ["dashboard.teamMember"] = "အဖွဲ့ဝင်",
        ["dashboard.myWork"] = "ကျွန်ုပ်၏အလုပ်များ",
        ["dashboard.employeeIntro"] = "အလုပ်များ၊ နောက်ဆုံးရက်များနှင့် သင့်တိုးတက်မှုကို တစ်နေရာတည်းတွင် ကြည့်နိုင်သည်။",
        ["dashboard.viewTasks"] = "အလုပ်များ ကြည့်ရန်",
        ["dashboard.loadingDashboard"] = "ဒက်ရှ်ဘုတ် ဖတ်နေသည်...",
        ["dashboard.tasksInProgressDesc"] = "လက်ရှိလုပ်ဆောင်နေသော အလုပ်များ",
        ["dashboard.noTasksInProgress"] = "လက်ရှိလုပ်ဆောင်နေသော အလုပ် မရှိပါ။",
        ["dashboard.todoUpcoming"] = "လုပ်ရန်နှင့် မကြာမီလာမည့်အလုပ်များ",
        ["dashboard.todoUpcomingDesc"] = "စတင်လုပ်ရန် သို့မဟုတ် မကြာမီလာမည့် အလုပ်များ",
        ["dashboard.noUpcomingTasks"] = "မကြာမီလာမည့် အလုပ် မတွေ့ပါ။",
        ["dashboard.overdueDesc"] = "နောက်ဆုံးရက် ကျော်လွန်နေသော အလုပ်များ",
        ["dashboard.noOverdueTasks"] = "နောက်ကျနေသော အလုပ် မရှိပါ။ ကောင်းပါတယ်။",
        ["dashboard.relatedTasks"] = "ဆက်စပ်အလုပ်များ",
        ["dashboard.tasksMarkedOn"] = "{date} တွင် မှတ်ထားသော အလုပ်များ",
        ["dashboard.noTasksForDay"] = "ဤနေ့အတွက် သတ်မှတ်ထားသော အလုပ် မရှိပါ။",
        ["dashboard.dueSoon"] = "မကြာမီ နောက်ဆုံးရက်ရောက်မည်",
        ["dashboard.managerTitle"] = "မန်နေဂျာ ဒက်ရှ်ဘုတ်",
        ["dashboard.teamView"] = "အဖွဲ့ မြင်ကွင်း",
        ["dashboard.myProjects"] = "ကျွန်ုပ်၏ စီမံကိန်းများ",
        ["dashboard.managerIntro"] = "သင့်အဖွဲ့၊ စီမံကိန်းအခြေအနေနှင့် အပတ်စဉ်အလုပ်တိုးတက်မှုကို တစ်နေရာတည်းတွင် ကြည့်နိုင်သည်။",
        ["dashboard.pendingTasksNotice"] = "အလုပ် {count} ခု စောင့်ဆိုင်းနေဆဲဖြစ်သည်။",
        ["dashboard.taskReport"] = "အလုပ် အစီရင်ခံစာ",
        ["dashboard.weeklyTaskProgress"] = "အပတ်စဉ် အလုပ်တိုးတက်မှု",
        ["dashboard.weeklyTaskProgressDesc"] = "အပတ်အလိုက် ပြီးစီးပြီးနှင့် စောင့်ဆိုင်းနေသော အလုပ်များ",
        ["dashboard.teamProgress"] = "အဖွဲ့ တိုးတက်မှု",
        ["dashboard.teamProgressDesc"] = "လက်ရှိအလုပ်ရှိသော အဖွဲ့ဝင်များ",
        ["dashboard.noAssignedWork"] = "ခွဲဝေထားသော အလုပ် မရှိသေးပါ။",
        ["dashboard.upcomingDeadlines"] = "မကြာမီရောက်မည့် နောက်ဆုံးရက်များ",
        ["dashboard.projectsEndingSoon"] = "မကြာမီပြီးဆုံးမည့် စီမံကိန်းများ",
        ["dashboard.ends"] = "ပြီးဆုံးရက်",
        ["dashboard.noUpcomingDeadlines"] = "မကြာမီရောက်မည့် နောက်ဆုံးရက် မရှိပါ။",
        ["dashboard.clickViewTasks"] = "\"အလုပ်များ ကြည့်ရန်\" ကိုနှိပ်ပြီး အသေးစိတ်ကြည့်ပါ",
        ["dashboard.complete"] = "ပြီးစီးမှု",
        ["dashboard.noProjectsForAccount"] = "ဤအကောင့်အတွက် စီမံကိန်း မရှိပါ။",
        ["dashboard.activeProjects"] = "လက်ရှိ စီမံကိန်းများ",
        ["dashboard.totalTasksMetric"] = "အလုပ် စုစုပေါင်း",
        ["dashboard.teamMembers"] = "အဖွဲ့ဝင်များ",
        ["dashboard.overdueTasks"] = "နောက်ကျနေသော အလုပ်များ",
        ["dashboard.allActive"] = "အားလုံး လက်ရှိ",
        ["dashboard.acrossProjects"] = "စီမံကိန်းများအတွင်း",
        ["dashboard.yourTeam"] = "သင့်အဖွဲ့",
        ["dashboard.needsAttention"] = "အာရုံစိုက်ရန် လိုသည်",
        ["dashboard.atRisk"] = "အန္တရာယ်ရှိ",
        ["dashboard.pending"] = "စောင့်ဆိုင်းနေသည်",
        ["dashboard.today"] = "ယနေ့",
        ["dashboard.done"] = "ပြီးစီးပြီး",
        ["dashboard.daysAgo"] = "လွန်ခဲ့သော {count} ရက်",
        ["dashboard.daysLeft"] = "{count} ရက် ကျန်",
        ["dashboard.dueToday"] = "ယနေ့ နောက်ဆုံးရက်",

        ["menu.DASHBOARD"] = "ဒက်ရှ်ဘုတ်",
        ["menu.DASHBOARD_ADMIN"] = "ဒက်ရှ်ဘုတ်",
        ["menu.DASHBOARD_MANAGER"] = "ဒက်ရှ်ဘုတ်",
        ["menu.DASHBOARD_EMPLOYEE"] = "ဒက်ရှ်ဘုတ်",
        ["menu.PROJECTS"] = "စီမံကိန်းများ",
        ["menu.PROJECTS_LIST"] = "စီမံကိန်းစာရင်း",
        ["menu.PROJECTS_ASSIGN"] = "စီမံကိန်း ခွဲဝေခြင်း",
        ["menu.TASKS"] = "လုပ်ငန်းများ",
        ["menu.TASKS_LIST"] = "လုပ်ငန်းစာရင်း",
        ["menu.TASKS_BOARD"] = "ကန်ဘန်းဘုတ်",
        ["menu.TASKS_ASSIGN"] = "လုပ်ငန်း ခွဲဝေခြင်း",
        ["menu.TASKS_BACKLOG"] = "လုပ်ငန်း နောက်ခံစာရင်း",
        ["menu.ISSUES_ADD"] = "ပြဿနာ ထည့်ရန်",
        ["menu.ISSUES_LIST"] = "ပြဿနာ စာရင်း",
        ["menu.REPORTS"] = "အစီရင်ခံစာများ",
        ["menu.REPORTS_TASKS"] = "လုပ်ငန်း အစီရင်ခံစာ",
        ["menu.REPORTS_TIMESHEET"] = "အချိန်မှတ်တမ်း",
        ["menu.REPORTS_OVERDUE"] = "နောက်ကျ လုပ်ငန်းများ",
        ["menu.REPORTS_EMPLOYEES"] = "ဝန်ထမ်း အစီရင်ခံစာ",
        ["menu.REPORTS_PROJECTS"] = "စီမံကိန်း တိုးတက်မှု",
        ["menu.REPORTS_ISSUES"] = "ပြဿနာ အစီရင်ခံစာ",
        ["menu.AUDIT_LOGS"] = "စနစ်မှတ်တမ်းများ",
        ["menu.USERS"] = "အသုံးပြုသူများ",
        ["menu.ROLES"] = "အခန်းကဏ္ဍများ",
        ["menu.DASHBOARD_WIDGETS"] = "အခန်းကဏ္ဍ အပြင်အဆင်များ",

        ["status.todo"] = "လုပ်ရန်",
        ["status.inprogress"] = "ဆောင်ရွက်နေသည်",
        ["status.done"] = "ပြီးဆုံး",
        ["status.overdue"] = "နောက်ကျ",
        ["status.blocked"] = "ပိတ်ဆို့",
        ["status.clear"] = "ရှင်း",
        ["status.resolved"] = "ဖြေရှင်းပြီး",
        ["status.uncompleted"] = "မပြီးသေး",
        ["priority.low"] = "နိမ့်",
        ["priority.medium"] = "အလယ်",
        ["priority.high"] = "မြင့်",
        ["status.active"] = "အသုံးပြုနေသည်",
        ["status.inactive"] = "အသုံးမပြုတော့ပါ",
        ["role.admin"] = "စီမံခန့်ခွဲသူ",
        ["role.manager"] = "မန်နေဂျာ",
        ["role.employee"] = "ဝန်ထမ်း",
        ["field.name"] = "အမည်",
        ["field.title"] = "ခေါင်းစဉ်",
        ["field.email"] = "အီးမေးလ်",
        ["field.phone"] = "ဖုန်း",
        ["field.created"] = "ဖန်တီးသည့်ရက်",
        ["field.taskCode"] = "အလုပ်ကုဒ်",
        ["field.ipAddress"] = "IP လိပ်စာ",
        ["project.manageAll"] = "စီမံကိန်းအားလုံးကို စီမံပါ။",
        ["project.employeesInProject"] = "ဤစီမံကိန်းရှိ ဝန်ထမ်းများ",
        ["project.yourAssigned"] = "သင့်အား ခွဲဝေထားသော စီမံကိန်းများ။",
        ["project.newProject"] = "စီမံကိန်းအသစ်",
        ["project.editProject"] = "စီမံကိန်းပြင်ရန်",
        ["project.createProject"] = "စီမံကိန်းဖန်တီးရန်",
        ["project.noProjectsYet"] = "စီမံကိန်းမရှိသေးပါ",
        ["project.createFirstProject"] = "စတင်ရန် ပထမဆုံးစီမံကိန်းကို ဖန်တီးပါ။",
        ["project.noAssignedProjects"] = "သင့်အား စီမံကိန်းမခွဲဝေထားသေးပါ။",
        ["project.projectName"] = "စီမံကိန်းအမည်",
        ["project.projectDescriptionOptional"] = "စီမံကိန်းဖော်ပြချက် (မဖြည့်လည်းရသည်)",
        ["project.updateTitle"] = "စီမံကိန်း အပ်ဒိတ်လုပ်မလား?",
        ["project.updateConfirm"] = "ဤစီမံကိန်းကို အပ်ဒိတ်လုပ်ရန် သေချာပါသလား?",
        ["project.createTitle"] = "စီမံကိန်း ဖန်တီးမလား?",
        ["project.createConfirm"] = "ဤစီမံကိန်းကို ဖန်တီးရန် သေချာပါသလား?",
        ["project.deleteTitle"] = "စီမံကိန်း ဖျက်မလား?",
        ["project.deleteConfirm"] = "ဤစီမံကိန်းကို ဖျက်ရန် သေချာပါသလား? ဤလုပ်ဆောင်ချက်ကို ပြန်ပြင်၍ မရပါ။",
        ["project.created"] = "စီမံကိန်းကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။",
        ["project.updated"] = "စီမံကိန်းကို အောင်မြင်စွာ အပ်ဒိတ်လုပ်ပြီးပါပြီ။",
        ["project.deleted"] = "စီမံကိန်းကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။",
        ["project.failedDelete"] = "စီမံကိန်းကို ဖျက်၍ မရပါ။",
        ["task.manageAll"] = "စီမံကိန်းအားလုံးရှိ အလုပ်များကို ကြည့်ရှု၍ စီမံပါ။",
        ["task.filterByProject"] = "စီမံကိန်းဖြင့် စစ်ထုတ်ရန်",
        ["task.yourAssigned"] = "သင့်အား ခွဲဝေထားသော အလုပ်များ။",
        ["task.newTask"] = "အလုပ်အသစ်",
        ["task.editTask"] = "အလုပ်ပြင်ရန်",
        ["task.createTask"] = "အလုပ် ဖန်တီးမည်",
        ["task.noTasksYet"] = "အလုပ်မရှိသေးပါ",
        ["task.createFirstTask"] = "စတင်ရန် ပထမဆုံးအလုပ်ကို ဖန်တီးပါ။",
        ["task.taskTitle"] = "အလုပ်ခေါင်းစဉ်",
        ["task.taskDescription"] = "အလုပ်ဖော်ပြချက်",
        ["task.selectProject"] = "စီမံကိန်းရွေးပါ...",
        ["task.loadingBoard"] = "ဘုတ်ကို ဖွင့်နေသည်...",
        ["task.dragHint"] = "အခြေအနေပြောင်းရန် အလုပ်များကို ကော်လံများကြား ဆွဲရွှေ့ပါ။",
        ["task.viewingArchived"] = "သိမ်းဆည်းထားသော အလုပ်များကို ကြည့်နေသည်။",
        ["task.backToBoard"] = "ဘုတ်သို့ ပြန်သွားမည်",
        ["task.archivedTasks"] = "သိမ်းဆည်းထားသော အလုပ်များ",
        ["task.archived"] = "သိမ်းဆည်းပြီး",
        ["task.dropTasksHere"] = "အလုပ်များကို ဤနေရာတွင် ချပါ",
        ["task.noTasks"] = "အလုပ်မရှိပါ",
        ["task.of"] = "မှ",
        ["task.due"] = "ပြီးဆုံးရန်",
        ["task.previousPage"] = "ယခင်စာမျက်နှာ",
        ["task.nextPage"] = "နောက်စာမျက်နှာ",
        ["task.createTitle"] = "အလုပ် ဖန်တီးမလား?",
        ["task.createConfirm"] = "ဤအလုပ်ကို ဖန်တီးရန် သေချာပါသလား?",
        ["task.updateTitle"] = "အလုပ် အပ်ဒိတ်လုပ်မလား?",
        ["task.updateConfirm"] = "ဤအလုပ်ကို အပ်ဒိတ်လုပ်ရန် သေချာပါသလား?",
        ["task.deleteTitle"] = "အလုပ် ဖျက်မလား?",
        ["task.deleteConfirm"] = "ဤအလုပ်ကို ဖျက်ရန် သေချာပါသလား? ဤလုပ်ဆောင်ချက်ကို ပြန်ပြင်၍ မရပါ။",
        ["task.archiveDoneTitle"] = "ပြီးဆုံးသော အလုပ်များ သိမ်းဆည်းမလား?",
        ["task.archiveDoneInProject"] = "ဤစီမံကိန်းရှိ ပြီးဆုံးသော အလုပ် {count} ခုကို သိမ်းဆည်းမလား? သိမ်းဆည်းပြီးပါက လက်ရှိမြင်ကွင်းများတွင် ဖျောက်ထားမည်။",
        ["task.archiveDoneAll"] = "မြင်နေရသော စီမံကိန်းအားလုံးရှိ ပြီးဆုံးသော အလုပ် {count} ခုကို သိမ်းဆည်းမလား? သိမ်းဆည်းပြီးပါက လက်ရှိမြင်ကွင်းများတွင် ဖျောက်ထားမည်။",
        ["task.noDoneToArchive"] = "သိမ်းဆည်းရန် ပြီးဆုံးသော အလုပ်မရှိပါ။",
        ["task.created"] = "အလုပ်ကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ!",
        ["task.updated"] = "အလုပ်ကို အောင်မြင်စွာ အပ်ဒိတ်လုပ်ပြီးပါပြီ!",
        ["task.deleted"] = "အလုပ်ကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ!",
        ["task.failedCreate"] = "အလုပ်ဖန်တီး၍ မရပါ။",
        ["task.failedDelete"] = "အလုပ်ဖျက်၍ မရပါ။",
        ["task.failedMove"] = "အလုပ်ကို ရွှေ့၍ မရပါ။ ထပ်မံကြိုးစားပါ။",
        ["task.failedArchiveDone"] = "ပြီးဆုံးထားသော အလုပ်များကို သိမ်းဆည်း၍ မရပါ။",
        ["task.archivedOneDone"] = "ပြီးဆုံးထားသော အလုပ် ၁ ခုကို သိမ်းဆည်းပြီးပါပြီ။",
        ["task.archivedManyDone"] = "ပြီးဆုံးထားသော အလုပ် {count} ခုကို သိမ်းဆည်းပြီးပါပြီ။",
        ["task.archive"] = "သိမ်းဆည်းမည်",
        ["role.rolesAccess"] = "အခန်းကဏ္ဍနှင့် ဝင်ခွင့်များ",
        ["role.rolesAccessDesc"] = "အခန်းကဏ္ဍများ၊ ဝင်ခွင့်များနှင့် ခွင့်ပြုချက်များကို စီမံပါ။",
        ["role.newRole"] = "အခန်းကဏ္ဍအသစ်",
        ["role.editRole"] = "အခန်းကဏ္ဍ ပြင်ရန်",
        ["role.createNewRole"] = "အခန်းကဏ္ဍအသစ် ဖန်တီးရန်",
        ["role.roleName"] = "အခန်းကဏ္ဍအမည်",
        ["role.searchByName"] = "အခန်းကဏ္ဍအမည်ဖြင့် ရှာပါ...",
        ["role.loadingRoles"] = "အခန်းကဏ္ဍများ ဖွင့်နေသည်...",
        ["role.noRolesYet"] = "အခန်းကဏ္ဍမရှိသေးပါ",
        ["role.createFirstRole"] = "စတင်ရန် ပထမဆုံးအခန်းကဏ္ဍကို ဖန်တီးပါ။",
        ["role.manageAccess"] = "ဝင်ခွင့် စီမံရန်",
        ["role.access"] = "ဝင်ခွင့်",
        ["role.assignAccess"] = "ဝင်ခွင့် ခွဲဝေရန်",
        ["role.accessHint"] = "စာမျက်နှာများသည် ဘယ်နေရာသို့ ဝင်နိုင်သည်ကို ထိန်းချုပ်ပြီး လုပ်ဆောင်ချက်များသည် ဘာလုပ်နိုင်သည်ကို ထိန်းချုပ်သည်။",
        ["role.createHint"] = "ဤအခန်းကဏ္ဍ မြင်နိုင်၊ လုပ်နိုင်သည့်အရာများကို ညာဘက်တွင် ရွေးပါ။ အခန်းကဏ္ဍနှင့်အတူ သိမ်းဆည်းမည်။",
        ["role.descriptionPlaceholder"] = "ဤအခန်းကဏ္ဍသည် ဘာလုပ်နိုင်သလဲ?",
        ["role.examplePlaceholder"] = "ဥပမာ မန်နေဂျာ၊ ကြည့်ရှုသူ",
        ["role.updateTitle"] = "အခန်းကဏ္ဍ အပ်ဒိတ်လုပ်မလား?",
        ["role.updateConfirm"] = "ဤအခန်းကဏ္ဍကို အပ်ဒိတ်လုပ်ရန် သေချာပါသလား?",
        ["role.createTitle"] = "အခန်းကဏ္ဍ ဖန်တီးမလား?",
        ["role.createConfirm"] = "ဤအခန်းကဏ္ဍကို ဖန်တီးရန် သေချာပါသလား?",
        ["role.deleteTitle"] = "အခန်းကဏ္ဍ ဖျက်မလား?",
        ["role.deleteConfirm"] = "ဤအခန်းကဏ္ဍကို ဖျက်ရန် သေချာပါသလား? ဤလုပ်ဆောင်ချက်ကို ပြန်ပြင်၍ မရပါ။",
        ["role.cannotDeleteTitle"] = "အခန်းကဏ္ဍကို ဖျက်၍မရပါ",
        ["role.cannotDeleteUsers"] = "ဤအခန်းကဏ္ဍတွင် အသုံးပြုသူ {count} ယောက် ရှိသောကြောင့် ဖျက်၍မရပါ။",
        ["role.created"] = "အခန်းကဏ္ဍကို အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။",
        ["role.updated"] = "အခန်းကဏ္ဍကို အောင်မြင်စွာ အပ်ဒိတ်လုပ်ပြီးပါပြီ။",
        ["role.deleted"] = "အခန်းကဏ္ဍကို အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။",
        ["role.failedDelete"] = "အခန်းကဏ္ဍကို ဖျက်၍ မရပါ။",
        ["role.saveAccess"] = "အသုံးပြုခွင့် သိမ်းမည်",
        ["role.accessConfigured"] = "အသုံးပြုခွင့်နှင့် ခွင့်ပြုချက်များကို သတ်မှတ်ပါ",
        ["role.permissionsHint"] = "မီနူးများသည် စာမျက်နှာဖွင့်ခွင့်ဖြစ်ပြီး ခွင့်ပြုချက်များသည် လုပ်ဆောင်ချက်များကို ဖွင့်ပေးသည်။",
        ["role.changeApplyAfterSave"] = "သိမ်းပြီးနောက် ပြောင်းလဲချက်များ သက်ရောက်ပါမည်။",
        ["role.noAccessItemsFound"] = "ဒေတာဘေ့စ်တွင် အသုံးပြုခွင့် အချက်အလက်များ မတွေ့ပါ။",
        ["role.noPagesMatchSearch"] = "ရှာဖွေမှုနှင့် ကိုက်ညီသော စာမျက်နှာ သို့မဟုတ် ခွင့်ပြုချက် မရှိပါ။",
        ["role.pagePermissionHint"] = "စာမျက်နှာအသုံးပြုခွင့်သည် ဤအပိုင်းကို ဖွင့်ခွင့်ပေးပြီး ခွင့်ပြုချက်များသည် အတွင်းရှိ ခလုတ်နှင့် လုပ်ဆောင်ချက်များကို အသုံးပြုခွင့်ပေးသည်။",
        ["role.nothingInsidePage"] = "ဤစာမျက်နှာအတွင်း ထပ်မံအသုံးပြုနိုင်သောအရာ မရှိပါ။",
        ["role.crudPermissions"] = "ဤစာမျက်နှာအတွက် CRUD ခွင့်ပြုချက်များ",
        ["role.willBeSaved"] = "သိမ်းဆည်းမည်",
        ["role.selectedItems"] = "ရွေးထားသောအရာ {count} ခု",
        ["role.accessSaved"] = "အသုံးပြုခွင့်များကို အောင်မြင်စွာ သိမ်းပြီးပါပြီ။",
        ["role.failedLoadAccess"] = "အသုံးပြုခွင့် အချက်အလက်များကို ဖတ်၍ မရပါ။ ထပ်မံကြိုးစားပါ။",
        ["role.failedSaveAccess"] = "အသုံးပြုခွင့်ကို သိမ်း၍ မရပါ။",
        ["common.unknown"] = "မသိပါ",
        ["common.saving"] = "သိမ်းနေသည်...",
        ["common.creating"] = "ဖန်တီးနေသည်...",
        ["common.searchRoles"] = "အခန်းကဏ္ဍ ရှာရန်",
        ["common.searchTasksByTitle"] = "အလုပ်ခေါင်းစဉ်ဖြင့် ရှာပါ...",
        ["common.allStatuses"] = "အခြေအနေအားလုံး",
        ["common.allPriorities"] = "ဦးစားပေးအားလုံး",
        ["common.budgetedHours"] = "ခန့်မှန်းနာရီ",
        ["common.budgetedHoursOptional"] = "ခန့်မှန်းနာရီ (မဖြည့်လည်းရသည်)",

        ["action.search"] = "ရှာမည်",
        ["action.reset"] = "ပြန်လည်သတ်မှတ်မည်",
        ["action.exportExcel"] = "Excel ထုတ်မည်",
        ["action.exportPdf"] = "PDF ထုတ်မည်",
        ["action.edit"] = "ပြင်မည်",
        ["action.delete"] = "ဖျက်မည်",
        ["action.add"] = "ထည့်မည်",
        ["action.create"] = "ဖန်တီးမည်",
        ["action.update"] = "အပ်ဒိတ်လုပ်မည်",
        ["action.save"] = "သိမ်းမည်",
        ["action.assign"] = "ခွဲဝေမည်",
        ["action.viewTasks"] = "လုပ်ငန်းများ ကြည့်မည်",
        ["action.archiveDone"] = "ပြီးဆုံးများ သိမ်းဆည်းမည်",
        ["action.clear"] = "ရှင်းမည်",

        ["result.loading"] = "ဖွင့်နေသည်...",
        ["result.saved"] = "အောင်မြင်စွာ သိမ်းပြီးပါပြီ။",
        ["result.created"] = "အောင်မြင်စွာ ဖန်တီးပြီးပါပြီ။",
        ["result.updated"] = "အောင်မြင်စွာ အပ်ဒိတ်ပြီးပါပြီ။",
        ["result.deleted"] = "အောင်မြင်စွာ ဖျက်ပြီးပါပြီ။",
        ["report.periodFilter"] = "ကာလ",
        ["report.daily"] = "နေ့စဉ် (ယနေ့)",
        ["report.monthly"] = "လစဉ် (ယခုလ)",
        ["report.yearly"] = "နှစ်စဉ် (ယခုနှစ်)",
        ["report.customRange"] = "စိတ်ကြိုက်အပိုင်းအခြား",
        ["report.selectedProject"] = "ရွေးထားသော စီမံကိန်း",
        ["report.openIssues"] = "ဖွင့်ထားသော ပြဿနာများ",
        ["report.lastActivity"] = "နောက်ဆုံး လုပ်ဆောင်ချက်",
        ["report.noTasksFound"] = "အလုပ်မတွေ့ပါ",
        ["report.noTasksFoundDesc"] = "လက်ရှိစစ်ထုတ်မှုများနှင့် ကိုက်ညီသော အလုပ် မရှိပါ။ ရှာဖွေမှု သို့မဟုတ် စစ်ထုတ်ချက်များကို ပြင်ဆင်ကြည့်ပါ။",
        ["report.noIssuesFound"] = "ပြဿနာမတွေ့ပါ",
        ["report.noIssuesFoundDesc"] = "လက်ရှိအစီရင်ခံ စစ်ထုတ်ချက်များနှင့် ကိုက်ညီသော ပြဿနာ မရှိပါ။",
        ["report.healthCritical"] = "အရေးကြီး",
        ["report.healthAtRisk"] = "အန္တရာယ်ရှိ",
        ["report.healthGood"] = "ကောင်းမွန်",
        ["report.delay"] = "နှောင့်နှေးချက်",
        ["report.blockedBy"] = "ပိတ်ဆို့နေသည်မှာ",
        ["report.noEffortEntries"] = "အချိန်မှတ်တမ်း မတွေ့ပါ",
        ["report.noEffortEntriesDesc"] = "လက်ရှိစစ်ထုတ်မှုများနှင့် ကိုက်ညီသော အချိန်မှတ်တမ်း မရှိပါ။",
        ["report.totalEstimatedEffort"] = "စုစုပေါင်း ခန့်မှန်းအားစိုက်မှု",
        ["report.variance"] = "ကွာခြားချက်",
        ["report.utilization"] = "အသုံးချမှု",
        ["report.timesheetEntries"] = "အချိန်မှတ်တမ်းပြဿနာများ",
        ["report.delayType"] = "နှောင့်နှေးမှုအမျိုးအစား",
        ["report.days"] = "ရက်",
        ["report.dueIn"] = "ကျန်ရှိချိန်",
        ["report.noReasonRecorded"] = "အကြောင်းပြချက် မမှတ်တမ်းတင်ထားပါ",
        ["report.noOverdueTasksDesc"] = "ကောင်းပါတယ်။ လက်ရှိစစ်ထုတ်မှုအရ နောက်ကျနေသော သို့မဟုတ် အန္တရာယ်ရှိသော အလုပ် မရှိပါ။",
        ["report.aheadOfSchedule"] = "အစီအစဉ်ထက် စောနေသည်",
        ["report.blockedOverdue"] = "ပိတ်ဆို့ / နောက်ကျ",
        ["report.noProjectData"] = "စစ်ထုတ်ချက်နှင့် ကိုက်ညီသော စီမံကိန်းအချက်အလက် မတွေ့ပါ။",
        ["report.employee"] = "ဝန်ထမ်း",
        ["report.assignedIssues"] = "တာဝန်ပေးထားသော ပြဿနာများ",
        ["report.openOverdue"] = "ဖွင့်ထား / နောက်ကျ",
        ["report.workload"] = "အလုပ်ပမာဏ",
        ["report.trend"] = "အလားအလာ",
        ["report.workloadHigh"] = "များ",
        ["report.workloadLight"] = "နည်း",
        ["report.workloadBalanced"] = "မျှတ",
        ["report.trendImproving"] = "တိုးတက်နေသည်",
        ["report.trendDeclining"] = "ကျဆင်းနေသည်",
        ["report.trendStable"] = "တည်ငြိမ်",
        ["report.noEmployeeData"] = "စစ်ထုတ်ချက်နှင့် ကိုက်ညီသော ဝန်ထမ်းအချက်အလက် မတွေ့ပါ။",

        ["validation.startDateRequired"] = "စတင်ရက် လိုအပ်ပါသည်။",
        ["validation.dueDateRequired"] = "ပြီးဆုံးရက် လိုအပ်ပါသည်။",
        ["validation.dueDateBeforeStart"] = "ပြီးဆုံးရက်သည် စတင်ရက်ထက် စော၍ မရပါ။",
        ["validation.projectNameRequired"] = "စီမံကိန်းအမည် လိုအပ်ပါသည်။",
        ["validation.endDateBeforeStart"] = "ပြီးဆုံးရက်သည် စတင်ရက်ထက် စော၍ မရပါ။",
        ["validation.taskTitleRequired"] = "လုပ်ငန်းခေါင်းစဉ် လိုအပ်ပါသည်။",
        ["validation.selectProjectRequired"] = "စီမံကိန်းတစ်ခုကို ရွေးပါ။",
        ["validation.selectTaskRequired"] = "လုပ်ငန်းတစ်ခုကို ရွေးပါ။",
        ["validation.issueTitleRequired"] = "ပြဿနာခေါင်းစဉ် လိုအပ်ပါသည်။",
        ["validation.roleNameRequired"] = "အခန်းကဏ္ဍအမည် လိုအပ်ပါသည်။",
        ["validation.passwordMinLength"] = "စကားဝှက်မှာ အနည်းဆုံး ၆ လုံး ရှိရမည်။",
        ["validation.usernameMinLength"] = "အသုံးပြုသူအမည်မှာ အနည်းဆုံး ၃ လုံး ရှိရမည်။",
        ["validation.usernameNoSpaces"] = "အသုံးပြုသူအမည်တွင် space မပါရပါ။",
        ["validation.usernameInvalidCharacters"] = "အသုံးပြုသူအမည်တွင် space မပါရပါ၊ စာလုံး၊ နံပါတ်၊ underscore (_) နှင့် dot (.) သာ အသုံးပြုနိုင်သည်။",
        ["validation.passwordMinLengthRule"] = "စကားဝှက်မှာ အနည်းဆုံး ၈ လုံး ရှိရမည်။",
        ["validation.passwordComplexityRule"] = "စကားဝှက်တွင် အနည်းဆုံး uppercase တစ်လုံး၊ lowercase တစ်လုံး၊ နံပါတ်တစ်လုံးနှင့် အထူးလက္ခဏာတစ်လုံး ပါရမည်။"
    };

    public static bool IsBurmeseCulture => CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("my", StringComparison.OrdinalIgnoreCase);

    public static string Text(string key, string fallback = "")
    {
        var catalog = IsBurmeseCulture ? Burmese : English;
        if (catalog.TryGetValue(key, out var value))
        {
            return value;
        }

        if ((IsBurmeseCulture ? English : Burmese).TryGetValue(key, out value))
        {
            return value;
        }

        return string.IsNullOrWhiteSpace(fallback) ? key : fallback;
    }

    public static string LocalizeDigits(string? value)
    {
        if (!IsBurmeseCulture || string.IsNullOrEmpty(value))
        {
            return value ?? string.Empty;
        }

        return value
            .Replace('0', '၀')
            .Replace('1', '၁')
            .Replace('2', '၂')
            .Replace('3', '၃')
            .Replace('4', '၄')
            .Replace('5', '၅')
            .Replace('6', '၆')
            .Replace('7', '၇')
            .Replace('8', '၈')
            .Replace('9', '၉');
    }

    public static string Number(int value) => LocalizeDigits(value.ToString(CultureInfo.InvariantCulture));

    public static string Number(long value) => LocalizeDigits(value.ToString(CultureInfo.InvariantCulture));

    public static string Number(decimal value, string format = "0.#") => LocalizeDigits(value.ToString(format, CultureInfo.InvariantCulture));

    public static string Number(double value, string format = "0.#") => LocalizeDigits(value.ToString(format, CultureInfo.InvariantCulture));

    public static string Menu(string menuCode, string fallback = "") => Text($"menu.{menuCode}", fallback);

    public static string PageTitle(string key, string fallback = "") => Text($"page.{key}", fallback);

    public static string PageDescription(string key, string fallback = "") => Text($"page.{key}.desc", fallback);

    public static string StatusLabel(AppTaskStatus status) => status switch
    {
        AppTaskStatus.InProgress => Text("status.inprogress", "In Progress"),
        AppTaskStatus.Done => Text("status.done", "Done"),
        _ => Text("status.todo", "To Do")
    };

    public static string PriorityLabel(TaskPriority priority) => priority switch
    {
        TaskPriority.High => Text("priority.high", "High"),
        TaskPriority.Medium => Text("priority.medium", "Medium"),
        _ => Text("priority.low", "Low")
    };

    public static string RoleName(string? roleName)
    {
        if (string.IsNullOrWhiteSpace(roleName))
        {
            return Text("common.unknown", "Unknown");
        }

        return roleName.Trim().ToLowerInvariant() switch
        {
            "admin" => Text("role.admin", "Admin"),
            "manager" => Text("role.manager", "Manager"),
            "employee" => Text("role.employee", "Employee"),
            _ => roleName
        };
    }

    public static string StatusName(string? statusName)
    {
        if (string.IsNullOrWhiteSpace(statusName))
        {
            return Text("common.unknown", "Unknown");
        }

        return statusName.Trim().Replace(" ", "", StringComparison.OrdinalIgnoreCase).ToLowerInvariant() switch
        {
            "todo" => Text("status.todo", "To Do"),
            "inprogress" => Text("status.inprogress", "In Progress"),
            "done" => Text("status.done", "Done"),
            "active" => Text("status.active", "Active"),
            "inactive" => Text("status.inactive", "Inactive"),
            "overdue" => Text("status.overdue", "Overdue"),
            "blocked" => Text("status.blocked", "Blocked"),
            "resolved" => Text("status.resolved", "Resolved"),
            "clear" => Text("status.clear", "Clear"),
            _ => statusName
        };
    }

    public static string PriorityName(string? priorityName)
    {
        if (string.IsNullOrWhiteSpace(priorityName))
        {
            return Text("common.unknown", "Unknown");
        }

        return priorityName.Trim().ToLowerInvariant() switch
        {
            "high" => Text("priority.high", "High"),
            "medium" => Text("priority.medium", "Medium"),
            "low" => Text("priority.low", "Low"),
            _ => priorityName
        };
    }

    public static string ActionName(string? actionName)
    {
        if (string.IsNullOrWhiteSpace(actionName))
        {
            return Text("common.unknown", "Unknown");
        }

        return actionName.Trim().ToLowerInvariant() switch
        {
            "create" or "created" or "add" or "added" => Text("action.create", "Create"),
            "update" or "updated" or "edit" or "edited" => Text("action.update", "Update"),
            "delete" or "deleted" => Text("action.delete", "Delete"),
            "assign" or "assigned" or "assignaccess" => Text("action.assign", "Assign"),
            "archive" or "archived" => Text("action.archiveDone", "Archive Done"),
            "login" => Text("common.signIn", "Sign In"),
            "logout" => Text("common.signOut", "Sign Out"),
            _ => actionName
        };
    }

    public static string ModuleName(string? moduleName)
    {
        if (string.IsNullOrWhiteSpace(moduleName))
        {
            return Text("common.unknown", "Unknown");
        }

        return moduleName.Trim().Replace(" ", "", StringComparison.OrdinalIgnoreCase).ToLowerInvariant() switch
        {
            "project" or "projects" => Text("page.projects", "Projects"),
            "task" or "tasks" => Text("page.tasks", "Tasks"),
            "user" or "users" => Text("page.users", "Users"),
            "role" or "roles" => Text("page.rolesAccess", "Roles & Access"),
            "issue" or "issues" => Text("page.issues", "Issues"),
            "audit" or "auditlog" or "auditlogs" => Text("page.auditLogs", "Audit Logs"),
            "dashboard" => Text("page.dashboard", "Dashboard"),
            "report" or "reports" => Text("menu.REPORTS", "Reports"),
            _ => moduleName
        };
    }

    public static string AuditDescription(string? description)
    {
        if (string.IsNullOrWhiteSpace(description))
        {
            return Text("common.noneRecorded", "None recorded");
        }

        var text = LocalizeDigits(description);
        if (!IsBurmeseCulture)
        {
            return text;
        }

        return text switch
        {
            var value when value.StartsWith("Created project ", StringComparison.OrdinalIgnoreCase) => $"စီမံကိန်း {value["Created project ".Length..]} ကို ဖန်တီးခဲ့သည်",
            var value when value.StartsWith("Deleted project ", StringComparison.OrdinalIgnoreCase) => $"စီမံကိန်း {value["Deleted project ".Length..]} ကို ဖျက်ခဲ့သည်",
            var value when value.StartsWith("Created new role ", StringComparison.OrdinalIgnoreCase) => $"အခန်းကဏ္ဍ {value["Created new role ".Length..]} ကို ဖန်တီးခဲ့သည်",
            var value when value.StartsWith("Deleted role ", StringComparison.OrdinalIgnoreCase) => $"အခန်းကဏ္ဍ {value["Deleted role ".Length..]} ကို ဖျက်ခဲ့သည်",
            var value when value.StartsWith("Updated access permissions for role ", StringComparison.OrdinalIgnoreCase) => $"အခန်းကဏ္ဍအသုံးပြုခွင့်များ ပြင်ဆင်ခဲ့သည်။ {value["Updated access permissions for role ".Length..]}",
            var value when value.StartsWith("Updated user ", StringComparison.OrdinalIgnoreCase) => $"အသုံးပြုသူ {value["Updated user ".Length..]} ကို ပြင်ဆင်ခဲ့သည်",
            _ => text
        };
    }

    public static string EscalationLabel(int level) => level switch
    {
        1 => IsBurmeseCulture ? "နိမ့်" : "Low",
        2 => IsBurmeseCulture ? "အလယ်" : "Medium",
        3 => IsBurmeseCulture ? "မြင့်" : "High",
        _ => Text("common.none", "None")
    };
}
