<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**" />
    <None Remove="artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Task\" />
    <Folder Include="Models\Project\" />
    <Folder Include="Models\Role\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.5" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.4" />
  </ItemGroup>

</Project>
