<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**" />
    <None Remove="artifacts\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <ProjectReference Include="..\..\TaskTrackingSystem.Shared\TaskTrackingSystem.Shared.csproj" />
  </ItemGroup>
</Project>
